services:
  ark-server:
    # Build the image from the Dockerfile in the current directory
    build: .
    container_name: ark-server
    restart: unless-stopped
    
    # Map the ports from the container to your host machine
    ports:
      - "7777:7777/udp"    # Game Port
      - "7778:7778/udp"    # Game Port
      - "27015:27015/udp"  # Steam Query Port
    
    volumes:
      - /home/bobi/Documents/docker/ark:/ark
      
    # --- SERVER CONFIGURATION ---
    # Edit these variables to customize your server
    environment:
      # Server Basics
      - SESSION_NAME="ARK - Diggatown"
      - SERVER_MAP=TheIsland
      - MAX_PLAYERS=10
      
      # Passwords (leave empty for no password)
      - SERVER_PASSWORD=my_server_password
      - ADMIN_PASSWORD=my_admin_password
      
      # Mods (comma-separated list of Workshop IDs)
      # Example: Structures Plus (S+)
      - GAME_MOD_IDS=731604991

      # Game Settings
      - SERVER_SETTINGS=ShowMapPlayerLocation=true,XPMultiplier=5.0

      # Other Settings
      - DISABLE_BATTLEYE=true # Set to 'false' to enable BattlEye

volumes:
  # Defines the named volume for data persistence
  ark-data: